name: Node Docker CI/CD

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop
      - 'feat/*'
      - 'fix/*'
      - 'breaking/*'

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Bump version
        id: bump
        run: |
          chmod +x ./bump-version.cjs
          VERSION=$(./bump-version.cjs)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Commit & push version bump
        if: steps.bump.outputs.version != ''
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "chore: bump version to ${{ steps.bump.outputs.version }}"
          git push origin ${{ github.ref }}

  setup-docker-tag:
    runs-on: ubuntu-latest
    needs: versioning
    outputs:
      docker_tag: ${{ steps.set-tag.outputs.tag }}
      vite_api_url: ${{ steps.set-tag.outputs.vite_api_url }}
    steps:
      - name: Définir le tag Docker
        id: set-tag
        run: |
          TARGET="${{ github.ref }}"
          if [[ "$TARGET" == "refs/heads/main" ]]; then
            echo "tag=prod" >> $GITHUB_OUTPUT
            echo "vite_api_url=${{ vars.VITE_API_URL_PROD }}" >> $GITHUB_OUTPUT
          elif [[ "$TARGET" == "refs/heads/develop" ]]; then
            echo "tag=pre-prod" >> $GITHUB_OUTPUT
            echo "vite_api_url=${{ vars.VITE_API_URL_PRE_PROD }}" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
            echo "vite_api_url=${{ vars.VITE_API_URL_PRE_PROD }}" >> $GITHUB_OUTPUT
          fi

  build-and-deploy:
    needs: [versioning, setup-docker-tag]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VITE_API_URL=${{ needs.setup-docker-tag.outputs.vite_api_url }}
          tags: |
            ghcr.io/likes-it/front:${{ needs.versioning.outputs.version }}
            ghcr.io/likes-it/front:${{ needs.setup-docker-tag.outputs.docker_tag }}
            ghcr.io/likes-it/front:latest
